modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL = "https://github.com/Team-Apiary/Impillagers/issues"

[properties]
"connector:placeholder" = true

[[mods]]
modId="impillagers"
version="1.6.0+1.21.1-multiloader"
displayName="Impillagers"
logoFile = "assets/impillagers/icon.png"
logoBlur = false
authors="Minico, TheBlindBandit6, BluePixelNinja, Smiileyface"
description="A total swamp overhaul mod with many new (and very quirky) residents to discover."
displayURL = "https://modrinth.com/mod/impillagers"

[[dependencies.impillagers]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"

[[dependencies.impillagers]]
modId = "fabric_api"
mandatory=true

[[dependencies.impillagers]]
modId="connector"
mandatory=true

[[dependencies.impillagers]]
modId="continuity"
mandatory=false